apiVersion: v1
kind: Secret
metadata:
  name: jfrog-cred
  namespace: taxi
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0YXhpMDYuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImMyRnBjbUZ0T2twbWNtOW5RREV5TXpRPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson